#!/usr/bin/env bash
# Runs on the HOST (not inside the container) via devcontainer.json's
# initializeCommand hook, BEFORE `docker compose up`. Extracts gh + claude
# auth from the host and writes them into .env.devcontainer so the
# container inherits them via env_file. Gitignored — never committed.
#
# Fails open: if a token can't be extracted we skip it instead of blocking
# the container start. The user can still `gh auth login` / `claude login`
# inside the container as a fallback.
set -euo pipefail

# Output path resolves relative to CWD, which is the workspace root when
# the devcontainer runtime invokes initializeCommand. BASH_SOURCE is
# unreliable here because this script may be piped via `bash -c` from a
# shim (the curl-based pattern), in which case there is no source file.
OUT="$(pwd)/.devcontainer/.env.devcontainer"
mkdir -p "$(dirname "$OUT")"
OS="$(uname -s)"

gh_token=""
claude_token=""

trim() {
  # Strips leading/trailing whitespace and any stray \r from tokens.
  # `gh auth token` can emit a trailing newline or space which then
  # survives into .env.devcontainer and breaks consumers that do a
  # strict string match on the value.
  printf '%s' "$1" | tr -d '\r\n' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
}

extract_from_keychain_macos() {
  # gh: uses macOS Keychain on modern versions. `gh auth token` reads it
  # transparently and prints the active token. Returns non-zero if logged out.
  if command -v gh >/dev/null 2>&1; then
    gh_token="$(trim "$(gh auth token 2>/dev/null || true)")"
  fi

  # claude: stored in Keychain under service "Claude Code-credentials".
  # The blob is JSON: { "claudeAiOauth": { "accessToken": "...", ... } }.
  # We extract the accessToken specifically since that's what
  # CLAUDE_CODE_OAUTH_TOKEN expects.
  if command -v security >/dev/null 2>&1 && command -v jq >/dev/null 2>&1; then
    local blob
    blob="$(security find-generic-password \
      -s "Claude Code-credentials" -a "$USER" -w 2>/dev/null || true)"
    if [[ -n "$blob" ]]; then
      claude_token="$(trim "$(printf '%s' "$blob" \
        | jq -r '.claudeAiOauth.accessToken // empty' 2>/dev/null || true)")"
    fi
  fi
}

extract_from_files_linux() {
  # gh on Linux (or macOS with --insecure-storage): token lives plain-text
  # in ~/.config/gh/hosts.yml under `oauth_token:`. Also honour the
  # already-exported GH_TOKEN env var if the user has one.
  if [[ -n "${GH_TOKEN:-}" ]]; then
    gh_token="$(trim "$GH_TOKEN")"
  elif command -v gh >/dev/null 2>&1; then
    gh_token="$(trim "$(gh auth token 2>/dev/null || true)")"
  elif [[ -f "$HOME/.config/gh/hosts.yml" ]]; then
    gh_token="$(trim "$(awk '/oauth_token:/ { print $2; exit }' \
      "$HOME/.config/gh/hosts.yml" 2>/dev/null || true)")"
  fi

  # claude on Linux: ~/.claude/.credentials.json with same JSON schema.
  if [[ -f "$HOME/.claude/.credentials.json" ]] && command -v jq >/dev/null 2>&1; then
    claude_token="$(trim "$(jq -r '.claudeAiOauth.accessToken // empty' \
      "$HOME/.claude/.credentials.json" 2>/dev/null || true)")"
  fi
}

case "$OS" in
  Darwin)
    extract_from_keychain_macos
    ;;
  Linux)
    extract_from_files_linux
    ;;
  *)
    # Windows (MINGW/CYGWIN) or anything else: best-effort file-based read.
    echo "init-secrets: unrecognized OS '$OS' — trying file-based extraction" >&2
    extract_from_files_linux
    ;;
esac

# Propagate the host's git identity so the container can sign commits
# with the correct email (required for GitHub "Verified" badges).
git_email="$(git config user.email 2>/dev/null || true)"
git_name="$(git config user.name 2>/dev/null || true)"

# Extract oauthAccount from the host's ~/.claude.json. This metadata
# (account UUID, email, org, subscription type) is what Claude Code
# checks to decide whether the token has full scope (including Remote
# Control). Without it, the CLI treats CLAUDE_CODE_OAUTH_TOKEN as
# inference-only and blocks features like /remote-control.
claude_account=""
CLAUDE_JSON_HOST="$HOME/.claude.json"
if [[ -f "$CLAUDE_JSON_HOST" ]] && command -v jq >/dev/null 2>&1; then
  claude_account="$(jq -c '.oauthAccount // empty' "$CLAUDE_JSON_HOST" 2>/dev/null || true)"
fi

{
  echo "# Auto-generated by .devcontainer/init-secrets.sh — DO NOT EDIT OR COMMIT."
  echo "# Regenerated on every container start/rebuild via initializeCommand."
  [[ -n "$gh_token"       ]] && echo "GH_TOKEN=$gh_token"
  [[ -n "$claude_token"   ]] && echo "CLAUDE_CODE_OAUTH_TOKEN=$claude_token"
  [[ -n "$git_email"      ]] && echo "GIT_AUTHOR_EMAIL=$git_email"
  [[ -n "$git_name"       ]] && echo "GIT_AUTHOR_NAME=$git_name"
  [[ -n "$claude_account" ]] && echo "CLAUDE_OAUTH_ACCOUNT=$claude_account"
} > "$OUT"
chmod 600 "$OUT"

# Report what we got so the user sees it in VSCode's "Dev Containers" output channel.
status_gh="missing"
status_claude="missing"
[[ -n "$gh_token"     ]] && status_gh="ok"
[[ -n "$claude_token" ]] && status_claude="ok"
echo "init-secrets: host=$OS  gh=$status_gh  claude=$status_claude  out=$OUT"
