#!/usr/bin/env bash
# Runs on the HOST (not inside the container) via devcontainer.json's
# initializeCommand hook, BEFORE `docker compose up`. Extracts gh + claude
# auth from the host and writes them into .env.devcontainer so the
# container inherits them via env_file. Gitignored — never committed.
#
# Fails open: if a token can't be extracted we skip it instead of blocking
# the container start. The user can still `gh auth login` / `claude login`
# inside the container as a fallback.
set -euo pipefail

# Output path resolves relative to CWD, which is the workspace root when
# the devcontainer runtime invokes initializeCommand. BASH_SOURCE is
# unreliable here because this script may be piped via `bash -c` from a
# shim (the curl-based pattern), in which case there is no source file.
OUT="$(pwd)/.devcontainer/.env.devcontainer"
mkdir -p "$(dirname "$OUT")"
OS="$(uname -s)"

gh_token=""
claude_token=""
claude_credentials_blob=""

trim() {
  # Strips leading/trailing whitespace and any stray \r from tokens.
  # `gh auth token` can emit a trailing newline or space which then
  # survives into .env.devcontainer and breaks consumers that do a
  # strict string match on the value.
  printf '%s' "$1" | tr -d '\r\n' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
}

extract_from_keychain_macos() {
  # gh: uses macOS Keychain on modern versions. `gh auth token` reads it
  # transparently and prints the active token. Returns non-zero if logged out.
  if command -v gh >/dev/null 2>&1; then
    gh_token="$(trim "$(gh auth token 2>/dev/null || true)")"
  fi

  # claude: stored in Keychain under service "Claude Code-credentials".
  # The blob is JSON: { "claudeAiOauth": { "accessToken": "...", ... } }.
  #
  # We extract BOTH:
  #   1. The accessToken alone (for CLAUDE_CODE_OAUTH_TOKEN env var — backward compat)
  #   2. The full blob (written to .claude-credentials.json so post-create
  #      can install it as ~/.claude/.credentials.json — this gives Claude
  #      Code full-scope auth including Remote Control, which env-var-based
  #      tokens explicitly lack by design)
  if command -v security >/dev/null 2>&1 && command -v jq >/dev/null 2>&1; then
    local blob
    blob="$(security find-generic-password \
      -s "Claude Code-credentials" -a "$USER" -w 2>/dev/null || true)"
    if [[ -n "$blob" ]]; then
      claude_token="$(trim "$(printf '%s' "$blob" \
        | jq -r '.claudeAiOauth.accessToken // empty' 2>/dev/null || true)")"
      claude_credentials_blob="$blob"
    fi
  fi
}

extract_from_files_linux() {
  # gh on Linux (or macOS with --insecure-storage): token lives plain-text
  # in ~/.config/gh/hosts.yml under `oauth_token:`. Also honour the
  # already-exported GH_TOKEN env var if the user has one.
  if [[ -n "${GH_TOKEN:-}" ]]; then
    gh_token="$(trim "$GH_TOKEN")"
  elif command -v gh >/dev/null 2>&1; then
    gh_token="$(trim "$(gh auth token 2>/dev/null || true)")"
  elif [[ -f "$HOME/.config/gh/hosts.yml" ]]; then
    gh_token="$(trim "$(awk '/oauth_token:/ { print $2; exit }' \
      "$HOME/.config/gh/hosts.yml" 2>/dev/null || true)")"
  fi

  # claude on Linux: ~/.claude/.credentials.json with same JSON schema.
  if [[ -f "$HOME/.claude/.credentials.json" ]] && command -v jq >/dev/null 2>&1; then
    claude_token="$(trim "$(jq -r '.claudeAiOauth.accessToken // empty' \
      "$HOME/.claude/.credentials.json" 2>/dev/null || true)")"
    claude_credentials_blob="$(cat "$HOME/.claude/.credentials.json" 2>/dev/null || true)"
  fi
}

case "$OS" in
  Darwin)
    extract_from_keychain_macos
    ;;
  Linux)
    extract_from_files_linux
    ;;
  *)
    # Windows (MINGW/CYGWIN) or anything else: best-effort file-based read.
    echo "init-secrets: unrecognized OS '$OS' — trying file-based extraction" >&2
    extract_from_files_linux
    ;;
esac

# Propagate the host's git identity so the container can sign commits
# with the correct email (required for GitHub "Verified" badges).
git_email="$(git config user.email 2>/dev/null || true)"
git_name="$(git config user.name 2>/dev/null || true)"

# Extract oauthAccount from the host's ~/.claude.json. This metadata
# (account UUID, email, org, subscription type) is what Claude Code
# checks to decide whether the token has full scope (including Remote
# Control). Without it, the CLI treats CLAUDE_CODE_OAUTH_TOKEN as
# inference-only and blocks features like /remote-control.
claude_account=""
CLAUDE_JSON_HOST="$HOME/.claude.json"
if [[ -f "$CLAUDE_JSON_HOST" ]] && command -v jq >/dev/null 2>&1; then
  claude_account="$(jq -c '.oauthAccount // empty' "$CLAUDE_JSON_HOST" 2>/dev/null || true)"
fi

# All values are double-quoted to handle spaces (GIT_AUTHOR_NAME),
# apostrophes (organizationName: "...com's Organization"), and other
# shell-special characters. The .env file is sourced by .zshrc/.bashrc
# via `set -a; source ...; set +a`, so quoting is load-bearing.
{
  echo "# Auto-generated by .devcontainer/init-secrets.sh — DO NOT EDIT OR COMMIT."
  echo "# Regenerated on every container start/rebuild via initializeCommand."
  [[ -n "$gh_token"       ]] && printf 'GH_TOKEN="%s"\n' "$gh_token"
  [[ -n "$claude_token"   ]] && printf 'CLAUDE_CODE_OAUTH_TOKEN="%s"\n' "$claude_token"
  [[ -n "$git_email"      ]] && printf 'GIT_AUTHOR_EMAIL="%s"\n' "$git_email"
  [[ -n "$git_name"       ]] && printf 'GIT_AUTHOR_NAME="%s"\n' "$git_name"
  # NOTE: CLAUDE_OAUTH_ACCOUNT is NOT written here. It contains JSON with
  # double quotes, apostrophes ("com's Organization"), and other characters
  # that are impossible to safely escape in docker-compose's .env format.
  # Instead, oauthAccount is written to .claude-account.json (see below)
  # and post-create.sh reads it from there.
} > "$OUT"
chmod 600 "$OUT"

# Write the full credentials blob alongside .env.devcontainer so
# post-create.sh can install it as ~/.claude/.credentials.json.
# This gives Claude Code full-scope auth (including Remote Control)
# because the CLI treats .credentials.json as a "full interactive
# login" — unlike CLAUDE_CODE_OAUTH_TOKEN which is explicitly
# restricted to inference-only by design.
CREDS_OUT="$(dirname "$OUT")/.claude-credentials.json"
if [[ -n "$claude_credentials_blob" ]]; then
  printf '%s' "$claude_credentials_blob" > "$CREDS_OUT"
  chmod 600 "$CREDS_OUT"
else
  rm -f "$CREDS_OUT"
fi

# Write oauthAccount as its own JSON file (not in .env — JSON with
# quotes and apostrophes is impossible to escape in docker-compose's
# env file format). post-create.sh merges this into ~/.claude.json.
ACCOUNT_OUT="$(dirname "$OUT")/.claude-account.json"
if [[ -n "$claude_account" ]]; then
  printf '%s' "$claude_account" > "$ACCOUNT_OUT"
  chmod 600 "$ACCOUNT_OUT"
else
  rm -f "$ACCOUNT_OUT"
fi

# Report what we got so the user sees it in VSCode's "Dev Containers" output channel.
status_gh="missing"
status_claude="missing"
[[ -n "$gh_token"     ]] && status_gh="ok"
[[ -n "$claude_token" ]] && status_claude="ok"
echo "init-secrets: host=$OS  gh=$status_gh  claude=$status_claude  out=$OUT"
